[workspace]
allow_dirty = false
changelog_update = false
dependencies_update = true
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore(release): release"
publish = false
publish_no_verify = true
semver_check = true

features_always_increment_minor = true

[[package]]
name = "skim"
publish = true
publish_no_verify = false
changelog_include = [
	"skim",
  "skim-common",
  "skim-tuikit",
	"shell",
	"plugin",
	"bin",
	"xtask",
	"e2e"
]
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_tag_enable = true
git_release_enable = true
git_tag_name = "v{{ version }}"
git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "skim-common"
publish = true
publish_no_verify = false
git_tag_enable = true
git_tag_name = "common-v{{ version }}"

[[package]]
name = "skim-tuikit"
publish = true
publish_no_verify = false
git_tag_enable = true
git_tag_name = "tuikit-v{{ version }}"

[[package]]
name = "e2e"
release = false
publish = false
[[package]]
name = "xtask"
release = false
publish = false

[changelog]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->⛰️ Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^refactor\\(clippy\\)", skip = true },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^chore: release", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
]

link_parsers = [
  { pattern = "#(\\d+)", href = "{{ remote.link }}/issues/$1" },
  { pattern = "RFC(\\d+)", text = "ietf-rfc$1", href = "https://datatracker.ietf.org/doc/html/rfc$1" },
]